<Label>:
	#text_size: self.size
	shorten: True
	padding_x: 5
	halign: "center"
	valign: "center"
	font_name: "D:/Program Files/Python37/Programs/smart-fridge-item-tracker/fonts/Poppins/Poppins-Light"
<Button>:
	text_size: self.size		#this keeps text from going off of the button
	font_size: "20sp"
	font_name: "D:/Program Files/Python37/Programs/smart-fridge-item-tracker/fonts/Poppins/Poppins-Light"